openapi: 3.0.3
info:
  title: Prices API
  version: 1.0.0
  description: Test REST API to retrieve the applicable price of a product for a given brand and date.

servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: Prices
    description: Endpoints for retrieving prices

paths:
  /api/v1/prices:
    get:
      tags:
        - Prices
      summary: Retrieves applicable price for a product and brand at a specific date and time
      description: Returns the applicable price of a product and brand at the given datetime.
        If multiple records are found, the one with the **highest priority** is returned.
      parameters:
        - name: date
          in: query
          required: true
          description: Date and time with format `2020-06-14-00.00.00`
          schema:
            type: string
            format: date-time
          example: "2020-06-14T10:00:00"
        - name: productId
          in: query
          required: true
          description: Product identifier
          schema:
            type: integer
          example: 35455
        - name: brandId
          in: query
          required: true
          description: Brand identifier
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Applicable price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponseDTO'
              examples:
                example1:
                  summary: Successful price response
                  value:
                    productId: 35455
                    brandId: 1
                    priceList: 1
                    startDate: "2020-06-14T00:00:00"
                    endDate: "2020-12-31T23:59:59"
                    price: 35.5
                    curr: "EUR"
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Bad Request"
                message: "Invalid parameter"
        '404':
          description: No price found for given parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Price Not Found"
                message: "Price Not Found"
        '500':
          description: Unexpected internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Internal Server Error"
                message: "Internal Server Error"

components:
  schemas:
    PriceResponseDTO:
      type: object
      description: Applicable price for product and brand
      properties:
        productId:
          type: integer
          example: 35455
        brandId:
          type: integer
          example: 1
        priceList:
          type: integer
          example: 1
        startDate:
          type: string
          format: date-time
          example: "2020-06-14T00:00:00"
        endDate:
          type: string
          format: date-time
          example: "2020-12-31T23:59:59"
        price:
          type: number
          format: double
          example: 35.5
        curr:
          type: string
          example: "EUR"

    ErrorResponse:
      type: object
      description: Error returned by the API
      properties:
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "Invalid parameters"
