name: Java CI - Build and Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Execute permission mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Run SnykScan
        uses: snyk/actions@master
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            JAVA_HOME: ${{ env.JAVA_HOME }}
            PATH: ${{ env.JAVA_HOME }}/bin:${{ env.PATH }}
            DEBUG: snyk*
        with:
            command: test
            args: --org=bool-basaur
